### ISSUE TITLE
tainicom.Aether.Physics2D.Common.Vector2

### ISSUE THREAD

**Issue by songshizhao** [tainicom/Aether.Physics2D#104]
I updated the nuget package to 1.6.1
after that, Vector2 type is type tainicom.Aether.Physics2D.Common.Vector2 instead of Microsoft.Xna.Framework.Vector2
I tried to changed the type, but 
spriteBatch.Draw(Animation.Texture, [playerBody.Position], source, Color.White, playerBody.Rotation, Origin, scale, spriteEffects, 0.0f);
playerBody.Position is [Physics2D] Common.Vector2 while here require Xna.Framework.Vector2
what is the best way to resolve this if i want to use higher version of this package, implement a convertor?

**Comment by nkast** [comment]
I understand this is inconvenient but I decided to make this breaking change sooner that later.
Inevitably it will be confusing for a lot of people If I were to maintain the current naming scheme.

From v1.5 the nuget package 'Aether.Physics2D' is a standalone library 
with no dependencies to 3rd party math libraries. 

For the MonoGame library (Vector2, Vector3 etc) and the MonoGame based diagnostics use the 'Aether.Physics2D.MG' 
and 'Aether.Physics2D.Diagnostics.MG'.

**Comment by songshizhao** [comment]
Thank you for your guide
I use 'Aether.Physics2D.MG' and 'Aether.Physics2D.Diagnostics.MG' instead. 
Problem resolved.
And I found Physics2D.MG cannot be used without Diagnostics.MG , Is it designed to be?

**Comment by nkast** [comment]
The physics library has no dependency on the Diagnostics. It's the other way around.
