### ISSUE TITLE
Objects not bouncing after collision.

### ISSUE THREAD

**Issue by GrooverFromHolland** [tainicom/Aether.Physics2D#106]
In my Monogame project I can't get objects to bounce/separate after collision. 
It's like restitution is not working. I use Aether.Physics2D.Diagnostics.MG vers. 1.6.1 and
Aether.Physics2D.Diagnostics.MG vers. 1.6.1 on Windows 11, Visual Studio 2019.

This is what I use to create my game objects:

```
       public  Body cueBall;
        World world = Game1.world;
   
     public CueBall()
        {
            cueBall = world.CreateCircle(Game1.BallBodyRadius, 1f, new Vector2(1000, 1000), BodyType.Dynamic);           
            cueBall.SleepingAllowed = false;           
            cueBall.Mass = 0.4f;
            cueBall.LinearDamping = 0.001f;
            cueBall.SleepingAllowed = false;
            cueBall.IsBullet = true;
            cueBall.Tag = "White";
            cueBall.FixtureList[0].Restitution = 1f;
            cueBall.FixtureList[0].CollisionCategories = Category.All;
        }

```
Can it be that Body. SetRestitution(float restitution) is obsolete?
I use  cueBall.FixtureList[0].Restitution = 1f; instead. 
I like to use this version, because the debugview is incuded and it is working great for scaling and placing objects.

I hope that Aether Phisics2D stays active for a long time, cause I love it!

**Comment by nkast** [comment]
The code looks good. It has to be something else in your code.
See also the similar code in the test testbed.
https://github.com/tainicom/Aether.Physics2D/blob/cb5ea4d46c234fafe43ce1010fbf2b73d6f63bea/Samples/Testbed/Tests/VaryingRestitutionTest.cs

**Comment by GrooverFromHolland** [comment]
Solved, it was  something else  in my code. In  protected override void Update(GameTime gameTime) I used  world.Step((float)gameTime.ElapsedGameTime.**TotalMilliseconds**) instead of  world.Step((float)gameTime.ElapsedGameTime.**TotalSeconds**).
