### ISSUE TITLE
Fix your default nuget package!

### ISSUE THREAD

**Issue by Shmellyorc** [tainicom/Aether.Physics2D#108]
Don't set your DEFAULT nuget package as your alpha, you will break peoples projects. Almost broke my whole game trying to fix my monogame content pipeline errors. I had to completely disable Aether Physics.

**Comment by Shmellyorc** [comment]
Other information:

1: Monogame uses dotnet core / dotnet standard 2.0 (for pipeline). "Monogame.Framework.Content.Pipeline.Portable" isnt used anymore/ obsolete. replace with:
https://www.nuget.org/packages/MonoGame.Framework.Content.Pipeline/

2: "Monogame.Framework.Portable" isnt used any more, replace with 3.8: https://www.nuget.org/packages/MonoGame.Framework.DesktopGL/
or
https://www.nuget.org/packages/MonoGame.Framework.WindowsDX/


3: Monogame standard content pipeline builder is now: https://www.nuget.org/packages/MonoGame.Content.Builder.Task/

If need proof: https://docs.monogame.net/articles/whats_new.html#removed-portable-assemblies

**Comment by nkast** [comment]
All -alpha packages are treated as preleseases by nuget & visual studio.
Other that the higher version there isn't anything else to it.

I don't see why moving back to the original version you had wasn't an option.

**Comment by nkast** [comment]
Please also see issue https://github.com/tainicom/Aether.Physics2D/issues/104 for a possible resolution.

**Comment by Shmellyorc** [comment]
@nkast  The main problem is using portable packages. They are not being used any more and will make your lovely and awesome physics framework pretty obsolete. I had real carnage when I bought in any Aether packages from monogame 3.8.

1. I couldn't use any of my content pipeline since monogame 3.8, uses this new standard.
2. It pretty much put my whole project in lockdown because after I removed it, it messed a bunch with my content pipeline stuff. So I had to do a clean wipe using "dotnet clean" which was another problem since I had to rebuild my content pipeline library to be used in the Monogame MGCB builder.
3. The portable will not work on the new standards of cross platform ecosystems because they are severely out of date. Current cross platform is used with dotnet core / dotnet standard using this new standard. Anyone using your Aether packages which uses "monogame portable" will not work on a Linux or Mac.

@nkast **Please review this, it is important**: https://docs.monogame.net/articles/whats_new.html#removed-portable-assemblies

**Comment by damian-666** [comment]
why not just build his netstandard aether and use that, add a project ref and not use the nuget.. then you can trace intot the physics youll end up forking it like everyone esle probably..

**Comment by damian-666** [comment]
see herer how https://github.com/damian-666/MGShadersXPlatform  i organize the content and game code and content  builder,, then add the debug view and the physics engine and it should work.. i can plug any phuysics fork to mine.  some graphcis netstandard shared code are linked to Monogame 3.8 GL as a proxy.  but its the EXE that link to MG dx , android or GL,  . i have 4 platfroms on one code with another fork like aether.  i do copy vecotrs to the monogame xna ones tho but its not big deal..  takes no time net6 is blazing fast i get 2000 fps on physics threadd and draw at 60hz last  frame, w/o locks.
