### ISSUE TITLE
Using the Monogame (XNA) version as source code

### ISSUE THREAD

**Issue by dclipca** [tainicom/Aether.Physics2D#109]
Is it possible to use the Monogame version as source code? My use case is serializing with MessagePack. Tried to copy the source code from the Physics2D folder and add the build constants `LEGACY_ASYNCADDREMOVE;XNAAPI;WINDOWS;MG;NET40` but still there are 700+ errors related to the `tainicom` and `XNA` vectors.

**Comment by nkast** [comment]
If you have created a new project then you probably have to exclude some of the files in /Common like the build-in Vector2.cs etc.

In those projects you will find the source files you need to include for MonoGame.
/Physics2D/Aether.Physics2D.NETSTANDARD2_0.MG.csproj (netstandard/net core) 
/Physics2D/Aether.Physics2D.WINDOWS.MG.csproj (net.framework)

**Comment by dclipca** [comment]
Thank you. I removed `/Common/Vector2.cs` and `/Common/Vector3.cs` and there are no errors.
Can you please explain why one has to add the source files from `/Physics2D/Aether.Physics2D.NETSTANDARD2_0.MG.csproj` or `/Physics2D/Aether.Physics2D.WINDOWS.MG.csproj`? Are those the files from `Content.Pipeline`. From my observations there are no errors if you just add the `Physics2D` and delete `/Common/Vector2.cs` and `/Common/Vector3.cs` inside it.

What am I getting wrong? I'm new to MonoGame so I maybe I'm missing something big.

**Comment by nkast** [comment]
In those projects you can see which files are used for the mg version, so you know which ones to exclude. 
Feel free to pick your own subset.
