### ISSUE TITLE
MultiInstance / Multithreading Possibilities.

### ISSUE THREAD

**Issue by matangpanchal** [tainicom/Aether.Physics2D#119]
Dear Sir,
I for some physics calculations, I have implemented this library in Windows Class Library using .NetFramework 4.6.1. I don't need any UI so I have not inherited my class from the Game Class, instead I implemented necessary functions and I found its working fine perfectly in Single instance.
Now problem is I have lots of combinations for which calculations needs to be done, so I wrapped my code in parallel.foreach. 
Here I have observed that most of the times it doesn't work as expected and doesn't solve some constraints. And for initial testing I am only executing 20 instances in parallel, which I may increase according to system CPU and ram Usage.
If I execute all 20 instances, one by one in a loop then they works perfectly. 
So , What I am doing is Possible with this Library ?
here is a sample piece of code:
=> **Few functions from DLL**
```c#      
	private void Constructor()
        {
            graphics = new GraphicsDeviceManager(game);
            game.Content.RootDirectory = "Content";
            game.IsMouseVisible = true;
            graphics.PreferredBackBufferWidth = commonClass.GAME_WIDTH;
            graphics.PreferredBackBufferHeight = commonClass.GAME_HEIGHT;
            graphics.ApplyChanges();
        }
 public void Initialize()
        {
            Camera = new Camera2D(game.GraphicsDevice, 25.0f);
            BatchEffect = new BasicEffect(game.GraphicsDevice);
            BatchEffect.VertexColorEnabled = true;
            BatchEffect.TextureEnabled = true;
            wld = new World();
            LoadContent();
            initComplete = true;
        }





public Tuple<bool, String> Update()
        {
            System.Diagnostics.Stopwatch st = new System.Diagnostics.Stopwatch();
            st.Start();
            double lastMilis = 0;
            double milis = 0;
            while (true)
            {
                wld.Step((float)1.0f / 60.00f);
                milis = st.Elapsed.TotalMilliseconds;
                if (milis - lastMilis > 500)
                {                    
                    commonClass.checkAndProcessResults();
                    if (commonClass.simulationResults == NewSamples.Demos.CommonClass.SimulationResults.Success)
                    {
                        return new Tuple<bool, string>(true, "");
                    }
                    else if (commonClass.simulationResults == NewSamples.Demos.CommonClass.SimulationResults.Failed)
                    {
                        return new Tuple<bool, string>(false, "");
                    }
                    if (st.Elapsed.TotalSeconds > 15)
                    {
                        return new Tuple<bool, string>(true, "Timeout");
                    }
                    lastMilis = milis;
                }

            }
```

==> Code From the Windows Forms
```vb.net
System.Threading.Tasks.Parallel.ForEach(list, Sub(item)
                                                              Dim a As New AetherC.Class1(item.Item3.ToArray())
                                                              a.Initialize()
                                                              a.BlockInfo = $"{item.Item1}_{item.Item2}"
                                                              Dim res As Tuple(Of Boolean, String) = a.Update()
                                                              a.SaveImage($"C:\3dmodels\temp\{item.Item1}_{item.Item2}_{res.Item1}.jpg", item.Item1.ToString)
                                                          End Sub)
```

**Comment by nkast** [comment]
If you are running one instance on each thread you should be fine.
(At least in theory ;-) )

I noticed that the code depends on real time. 
That means that on each run some simulations will run a random number of steps. Could that be related to the checks you are doing?

**Comment by nkast** [comment]
Additionally, make sure that you are not sharing instances of objects between worlds. (Bodies, Fixures Shapes, etc).
Check callback events in your code and ensure they are thread safe, not shared between world.  
World run some methods in parallel, Turn off multithreading to see if that affects the result.
Serialize the state for each world/step into files. The resulting files should be identical on each run.

**Comment by damian-666** [comment]
*also if you  are depending on precise timers, the default setting is off
by as much as a whole frame, its terrible.*

*If you test the simple call to Sleep(1) wth stopwatch, you will get
results between 1 and 16 ms ( 60 fps , 1 frame is 16ms)*

if you need precise timing of physics calls you must use Dllimport of
windows api

timeBeginPeriod( int millsec);

in my looo i use a timer to keep a stable refresh on anther there and dont
use the game update.   but untill i learned this i was lost.
timeBeginPeriod( 4)  //good enough for mine, you  set to 1 for 1 ms
resolution, but that might have some tradeoffs

all the wait handles, timers and sync mechanisms rely on this as well.
https://hero.handmade.network/forums/game-discussion/t/8612-what_does_timebeginperiod_actually_do
https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/
 ,unexpected timeouts, dropped frames,  can result.  I avoid all syncing
but the phsycis engine
also the static variables you must make sure are thread local.

*after windows 10 was updated the call does not affect other processes and
you don't have to call TimeEndPeriod, it will be reset for better power
consumption when your app closes. *

**Comment by matangpanchal** [comment]
> 

**Thank you for prompt reply and suggesting few Points to check.** 
I have tried but still problem is there with multi threads, please read below my explanations.


> I noticed that the code depends on real time.
> That means that on each run some simulations will run a random number of steps. Could that be related to the checks you are doing?

```
if (milis - lastMilis > 500)
                {                    
                    commonClass.checkAndProcessResults();
}
```
Are you referring the above code in Update method where I am waiting for 500ms before checking results ? I made those changes with the hope that it will give objects some frames to move and try to solve the constraints, otherwise World is stepping without any extra delay other than condition checking.

**I have never worked with any such engines, so please advice me where ever necessary.**


> Additionally, make sure that you are not sharing instances of objects between worlds. (Bodies, Fixures Shapes, etc).

Not a single object is sharing world, that I have checked

> Check callback events in your code and ensure they are thread safe, not shared between world.
> Serialize the state for each world/step into files. The resulting files should be identical on each run.


I am not aware of these both points, can you please explain ?


> World run some methods in parallel, Turn off multithreading to see if that affects the result.

I tried disabling multithreading using code below, still same problem occurs.
```c#
            wld.ContactManager.PositionConstraintsMultithreadThreshold = int.MaxValue;
            wld.ContactManager.PositionConstraintsMultithreadThreshold = int.MaxValue;
            wld.ContactManager.CollideMultithreadThreshold = int.MaxValue;
```

**Comment by matangpanchal** [comment]
Also I request you to have a look at my code for better understanding of what I may have missed or done wrong.
Currently I am passing few diameters of Circle to the DLL using constructor, and DLL's job is to fit circles of those diameters in the given Circle Container. With specified margins among objects and container.
I have uploaded code of both on GDrive [here](https://drive.google.com/file/d/1mX-s_aoY3EnR1mfaNbVjysPlO8OL86wC/view?usp=share_link).

Images below shows problem I am facing., the First image is result from threading, and 2nd image is result from single run.

Where in 1st image, Its not able to fit circles in a container and in the second image, its able to fit circles.
**I am looking forward to have some suggestions from you experienced guys on this.**

![7_1_False__T](https://user-images.githubusercontent.com/16164757/236614252-b51986e3-07cb-429b-9394-a5065d30a4b7.jpg)
![7_1_True_](https://user-images.githubusercontent.com/16164757/236614255-edafe4a0-3191-4b9c-887f-648d38f9c9c6.jpg)
Thanks,
Awaiting your reply.

**Comment by nkast** [comment]
Here is not the place to get help fixing sync issues in your code.

You need to at least pin-point to an exact issue with the library and provide a simple sample project to reproduce it, otherwish I am afraid I can't do anything about that.

**Comment by nkast** [comment]
Look at the SerializationTest in Testbed as a example.
https://github.com/tainicom/Aether.Physics2D/blob/bd8738dbdecc60aaa3ea61388289f6f7df123472/Samples/Testbed/Tests/SerializationTest.cs#L190

**Comment by matangpanchal** [comment]
> Here is not the place to get help fixing sync issues in your code.
> 
> You need to at least pin-point to an exact issue with the library and provide a simple sample project to reproduce it, otherwish I am afraid I can't do anything about that.

Yes, I can understand it. Actually, I don't have any clue that is that a issue with the library or my implementation.
Nevermind, I am very thankful to you for your support. 
I will figure out something.
Thank You.
