### ISSUE TITLE
ArgumentException when playing with Breakablebodiesandexplosions

### ISSUE THREAD

**Issue by guFalcon** [tainicom/Aether.Physics2D#31]
Happens quite often when exploding the scene and then wildly dragging single parts around causing collisions (drag and release mouse-button)...
![image](https://user-images.githubusercontent.com/7469819/31631630-91218f62-b2ba-11e7-98ad-86e1c5f1ffe2.png)
In world.cs.
JointList is empty.

**Comment by guFalcon** [comment]
Very nice work, btw :)
I think I want to see how far I can go with the fluid dynamics and a metaballs shader... when I find the time.

**Comment by nkast** [comment]
Thanks @guFalcon 

So what happens it's that when the BreakableBody breaks and MainBody is removed this also remove any attacked joints. In this case the _fixedMouseJoint.

At the moment I don't think it's safe to re-attach the joints to another body. 
There are couple of other thing that BreakableBody does not take care of, like collision categories, Controllers, etc

I don't think this class belongs to the core engine. I will just move it to the Samples or to PhysicsLogic.
