### ISSUE TITLE
Assertion Failed At samples.WINDOWS.MG AdvancedDemo1,5

### ISSUE THREAD

**Issue by chjhong** [tainicom/Aether.Physics2D#57]
**version**
git clone origin/master
git clone from commit 830cdbd865a5e5fbd1af8b13fa355b04ba988a37
last pull at commit 8c53539b02d6f72eda72b9f7ecad05df916ba218

**error**
Assertion Failed

**info**
Samples.WINDOWS.MG / Advanced Samples
* Texture to vertices / advancedDemo1.cs
* breakable bodies and expolsions  / advancedDemo5.cs

\Aether.Physics2D\Physics2D\Common\Decomposition\BayazitDecomposer.cs
line34: `Debug.Assert(vertices.IsCounterClockWise());`

**Comment by nkast** [comment]
Thank @aron3097 

It looks like I introduced a bug on Bayazit and Flipcode in https://github.com/tainicom/Aether.Physics2D/commit/982e422ead68b72d6968b4232d7b4e740f21c96f.
