### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by andrew-sidereal** [tainicom/Aether.Physics2D#59]
Hi there,

I have been looking for a more up-to-date fork of the wonderful Farseer engine. Yours seems to be one of the best options, but before I migrate my game to use your engine instead of Farseer, I'd like to confirm that this is production ready to the best of your knowledge and what any possible issues may be, if any. Alternatively, are there any other Forks you would recommend I investigate?

Thank you!
Andrew

**Comment by nkast** [comment]
Hi @alundgren04,

I am trying to make the engine as robust as possible but I can't quarantine that is bug-free. There are bits that need a bit more attention. 

 In terms of the API there are a couple of things that might change but I will try to keep those changes at minimum from now on.

Interesting progress is hapening in the C++ space. In https://github.com/erincatto/Box2D and https://github.com/louis-langholtz/Box2D
