### ISSUE TITLE
Deterministic Networking

### ISSUE THREAD

**Issue by andrew-sidereal** [tainicom/Aether.Physics2D#63]
Is there any way to make Aether deterministic or is that fundamentally impossible due to how it uses multithreading? This is required in order to utilize a network synchronization approach known as Deterministic Lockstep. https://gafferongames.com/post/deterministic_lockstep/

**Comment by nkast** [comment]
This has similarities to a discussion I had about removing locking.
You could partition contacts into clusters that you know that do not have pairs/bodies on other clusters.
This way the contacts are proceed at the same order each time.
This would be a multi-step process and requires a barrier sync on each step and the clusters might not be    of equal size which leaves cores waiting for the longest batch. The processes of partitioning adds extra overhead, you might try to use multithreading to speed it up which makes locking between bodies unavoidable after all and the entire process overall slower that before either way. This can only be useful for SIMD processing or GPU processing (which requires a massive rewrite, grouping by shape type compilation, and I suppose latest compute shaders already has some type of synchronization?)

In case of determinism, you'd also have to partition the bodies in equal clusters to account for 1/2/3/4/6/8/16 cores/threads. Therefore you either have cores sitting, or the clusters have a small number of bodies each. (144 clusters/threads is divisible by 1,2,3,4,6,8,16 cores)

Additionally you still have to account for differences between different CPU and problems with floating point. In C++ you will usually have to turn of some optimizations to make all platforms behave the same.
But in .Net this is out of your control, code generation and optimization is done by the clr, be it .net 4.0-7.0, xamarin, net.core, etc.

**Comment by nkast** [comment]
Some more info about determinism and Box2D.
https://github.com/erincatto/Box2D/wiki/FAQ#determinism
