### ISSUE TITLE
how to get the contact point from TOI?

### ISSUE THREAD

**Issue by benblo** [tainicom/Aether.Physics2D#66]
Hi,
I'm using `TimeOfImpact.CalculateTimeOfImpact()` to perform a shape-cast, which gives me back the TOI from which I can compute the position of my casting shape at the TOI.
But I'm also interested in the contact point/normal itself, and noticed the [CalculateTimeOfImpact](https://github.com/tainicom/Aether.Physics2D/blob/7f223ed0071f25b1607fc351ba42bf0a016bbefd/Physics2D/Collision/TimeOfImpact.cs) inline doc says to `use Distance() to compute the contact point and normal at the time of impact`... however I'm not sure what `Distance()` this is referring to, and I didn't find a particularly easy way to do this.

Best I managed was to use `Distance.ComputeDistance()`, but that seems super inefficient and redundant as it's already done by `TimeOfImpact.CalculateTimeOfImpact()`. Also, I'm not sure I'm handling all the cases in the same way as `CalculateTimeOfImpact`.

Is there a better way to do this?
And is there a reason `CalculateTimeOfImpact` doesn't output more info out of the box?

Thanks!

**Comment by nkast** [comment]
Hi @benblo,

I am not familiar with TimeOfImpact.CalculateTimeOfImpact(). I think you can get the right answer if you ask this in Box2D forums. The library is a port of Box2D and should work identically (with minor changes to method names).

**Comment by benblo** [comment]
Thanks, I'll try that!

**Comment by nkast** [comment]
From what I can tell TimeOfImpact.CalculateTimeOfImpact() is used internally by the solver to find a fast    approximation of TOI (an upper bound), that is used to step the TOI at the next TOI. The solver then will find the actual TOI of collision through a number of iterations. It's not an accurate result and it's not supposed to be used outside the engine.

~In box2D those functions are internal. Farseer probably had them public to be visible by the testbed.~ I will make those internal to avoid further confusions to end users. To resolve the issue with testbed I will make use of [Friend Assemblies](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/assemblies-gac/friend-assemblies).

**EDIT**
CalculateTimeOfImpact() is public in Box2D.

**Comment by benblo** [comment]
Hmm... I'm surprised you're saying it's "not an accurate result", I've been using it in a shipped game and haven't noticed any imprecision issues.
What approach would you recommend for raycasting/shapecasting?

**Comment by nkast** [comment]
If you subscribe to `BeginContact` or `OnCollision` you can get the new `Contact` at the time the collision occurs. From there you can access the `Contact.Manifold` or call  `Contact.GetWorldManifold`.
The Manifold contains the contact points and the normal.

This works only during the simulation/stepping. I don't know how you can predict a collision without actually running the simulation. For one thing you are ignoring third objects that might collide with and disrupt the position of one of the two objects you are testing.
