### ISSUE TITLE
Infinite loop/hang when bodies in the same position initially

### ISSUE THREAD

**Issue by Mathetis** [tainicom/Aether.Physics2D#68]
Hey, 

I am seeing an infinite loop in Aether. I believe it can be avoided by preventing two bodies from initially sharing the same location, but I am concerned about the presence of such a hang generally.

This is using a .NET standard 2.0 build of Aether. It is optimized. I do not see it happen with a debug build, or I have not yet. This is using two dynamic bodies. They each have one fixture in the shape of a square. They have velocity, angular velocity, and are rotated.  When the objects share the same position or overlap significantly (I think), it locks up in the following code on this line:

                s = EdgeSeparation(poly1, ref xf1To2, edge, poly2);

This is the loop:

            // Perform a local search for the best edge normal.
            for (; ; )
            {
                if (increment == -1)
                    edge = bestEdge - 1 >= 0 ? bestEdge - 1 : count1 - 1;
                else
                    edge = bestEdge + 1 < count1 ? bestEdge + 1 : 0;

                s = EdgeSeparation(poly1, ref xf1To2, edge, poly2);

                if (s > bestSeparation)
                {
                    bestEdge = edge;
                    bestSeparation = s;
                }
                else
                {
                    break;
                }
            }

Note that because this is a release build, more detail is not available. The trace for Aether is here ( I removed the prefix for readability):

 .Collision.Collision.FindMaxSeparation(out int edgeIndex, .Shapes.PolygonShape poly1, ref Transform xf1, .Shapes.PolygonShape poly2, ref Transform xf2)	Unknown
 .Collision.Collision.CollidePolygons(ref .Manifold manifold, .Shapes.PolygonShape polyA, ref Transform transformA, .Shapes.PolygonShape polyB, ref Transform transformB)	Unknown
 .Dynamics.Contacts.Contact.Evaluate(ref .Manifold manifold, ref Transform transformA, ref Transform transformB)	Unknown
 .Dynamics.Contacts.Contact.Update(tainicom.Aether.Physics2D.Dynamics.ContactManager contactManager)	Unknown
 .Dynamics.ContactManager.Collide()	Unknown
 .Dynamics.World.Step(float dt, ref tainicom.Aether.Physics2D.Dynamics.SolverIterations iterations)	Unknown
 .Dynamics.World.Step(float dt)	Unknown

Here is the available state info:

	edgeIndex	0	int
		
	poly1	{Collision.Shapes.PolygonShape}	Collision.Shapes.PolygonShape
		ChildCount	1	int
		Density	4.5	float
		MassData	{Collision.Shapes.MassData}	Collision.Shapes.MassData
		Normals	Count = 4 Vertices = "{X:0.7071068 Y:0.7071068} {X:-0.7071068 Y:0.7071068} {X:-0.7071068 Y:-0.7071068} {X:0.7071068 Y:-0.7071068}"	Vertices
		Radius	0.01	float
		ShapeType	Polygon	Collision.Shapes.ShapeType
		Vertices	Count = 4 Vertices = "{X:0.09375 Y:0} {X:0 Y:0.09375} {X:-0.09375 Y:0} {X:0 Y:-0.09375}"	Vertices
		_2radius	0	float
		_density	4.5	float
		_normals	Count = 4 Vertices = "{X:0.7071068 Y:0.7071068} {X:-0.7071068 Y:0.7071068} {X:-0.7071068 Y:-0.7071068} {X:0.7071068 Y:-0.7071068}"	Vertices
		_radius	0.01	float
		_vertices	Count = 4 Vertices = "{X:0.09375 Y:0} {X:0 Y:0.09375} {X:-0.09375 Y:0} {X:0 Y:-0.09375}"	Vertices

		
	poly2	{Collision.Shapes.PolygonShape}	Collision.Shapes.PolygonShape
		ChildCount	1	int
		Density	4.5	float
		MassData	{Collision.Shapes.MassData}	Collision.Shapes.MassData
		Normals	Count = 4 Vertices = "{X:0.7071068 Y:0.7071068} {X:-0.7071068 Y:0.7071068} {X:-0.7071068 Y:-0.7071068} {X:0.7071068 Y:-0.7071068}"	Vertices
		Radius	0.01	float
		ShapeType	Polygon	Collision.Shapes.ShapeType
		Vertices	Count = 4 Vertices = "{X:0.09375 Y:0} {X:0 Y:0.09375} {X:-0.09375 Y:0} {X:0 Y:-0.09375}"	Vertices
		_2radius	0	float
		_density	4.5	float
		_normals	Count = 4 Vertices = "{X:0.7071068 Y:0.7071068} {X:-0.7071068 Y:0.7071068} {X:-0.7071068 Y:-0.7071068} {X:0.7071068 Y:-0.7071068}"	Vertices
		_radius	0.01	float
		_vertices	Count = 4 Vertices = "{X:0.09375 Y:0} {X:0 Y:0.09375} {X:-0.09375 Y:0} {X:0 Y:-0.09375}"	Vertices

	count1	4	int
	edge	0	int
	bestEdge	3	int
	increment	1	int

Any thoughts?  The world is conditioned with a ratio of 128 physics units to 1 pixel.

**Comment by nkast** [comment]
It would be nice if you could give the position and velocity of the objects as well.
One though is to [serialize](https://github.com/tainicom/Aether.Physics2D/blob/7f223ed0071f25b1607fc351ba42bf0a016bbefd/Samples/Testbed/Framework/Test.cs#L110-L113) the world state before each step, this way we could reproduce the bug.

>> Any thoughts? The world is conditioned with a ratio of 128 physics units to 1 pixel.

Is that correct? The engine works with meters as it's units, so if a sprite on screen is 128x128 px, does that  mean that the body is 16 kilometers wide, or am I reading this the other way around?

**Comment by Mathetis** [comment]
I'll look at getting the specific state, thanks.

Sorry, I miscommunicated. A 128 pixel object would be 1 meter in engine terms.  So the 18 cm squares in the example above work out to 23 pixels or so.

I suspect a 16km fixture would not work well ;-). Though this is a large world, the fixtures in it stay 1ish meters. It is my understanding that's the way to use it.

**Comment by nkast** [comment]
Indeed, My first thought was an issue with precision but I misunderstood.

 It's also strange that you only see this under release. If you can get the state of the world just before the crash it would be very helpful.

**Comment by Mathetis** [comment]
Hey, it took a little wrangling, but here is a the serialized world just before the step that caused the hang. The step was ~0.0083333 seconds. 

I noticed that it does not occur when the fixtures are triangles. Squares reveal it.

I used this to serialize:

                    WorldSerializer.Serialize(world_, stream);

I had to remove the tags before serializing because they can't be serialized with the world, but otherwise it should be all there.

[frame_1_0.0166667.zip](https://github.com/tainicom/Aether.Physics2D/files/2847183/frame_1_0.0166667.zip)

**Comment by nkast** [comment]
Hi @Mathetis 

I manage to load the world from frame_1_0.0166667.xml
 
When I step it with Step(0.0083333f) I don't see any problem, it works fine.

**Comment by nkast** [comment]
> This is using a .NET standard 2.0

How did you build that? have you tried with the official .net framework?
Try to use a stable version like 4.5 which has been proven stable.

**Comment by nkast** [comment]
The cause of the error is definitely having bodies at the same position. In the world I can see 3 dynamic bodies at position [1.5625, 9.882813]. The engine does not support that, it can lead to all kinds of unexpected behavior. The reason it hang at .NET standard Release and not with .Net framework is probably because of different optimizations taking place in .NetCore.
     
I don't think it's possible to defend against such situations as there is not a right way to resolve it.

**Comment by Mathetis** [comment]
Hey, thanks for confirming. I will look at making the engine guard against this condition before getting to Aether. I think you are right about .NET standard's optimizations, as it does not happen in .NET standard's debug mode. I am using .NET standard because I am developing for a number of platforms. 

Btw, no code changes were required for .NET standard. I have simple added a .NET standard project under Physics2D.

**Comment by Mathetis** [comment]
Hi, I am noticing in general that if dynamic bodies end up tunneling into other bodies, whether dynamic or static, I see the engine rail in methods like SolveTOIPositionConstraints . 

See here for a similar report in box2d:  http://www.box2d.org/forum/viewtopic.php?t=8154

This sounds like the same sort of unsupported case? Is there any way to detect this situation before creating a body using Aether? Perhaps placing a sensor and checking for contacts, and then placing the body? Or is there a way to detect situations where they get stuck? The case of occupying exactly the same spot is a bit easier to detect, obviously.

**Comment by nkast** [comment]
You can enable the IsBullet for fast moving bodies to prevent tunneling. 

If the body was initially created trapped between two walls then the engine will not know what to do, it 's an impossible situation in real world. 

I don't know how you can detect this beforehand. Maybe you could listen in some of the collision events/contact filtering, etc and then add the body.
In the event you could try to fix those situations, I know this is easy to say than done. 
You could iterate the contacts and manifolds to 
get the collision points between bodies and then disable the collision or remove the body or throw an exception, each situation would require a different approach.
