### ISSUE TITLE
Spawning coordinate of Body

### ISSUE THREAD

**Issue by Hardkaise** [tainicom/Aether.Physics2D#71]
Hello Tainicom,

I am using your physics engine to do a project by combining with it a graphics library.

I have a problem:

When I define the position of the body, it doesn't match with the coordinate given.
Let me explain more in details: I gave some coordinates to the position attribute of Body and the same coordinates to my graphics library. Result ? Spawning point of the graphics library is on the top left corner and the spawning point of Aether.Physics2D is in the center. So I have a hitbox shift every time.

I would like to know if it's possible to change the spawning point of Aether.Physics2D to the top left corner, if it changes things in physics engine running and how it's possible.

I really appreciate your physics engine, it's working well associate to my personal project.

I thank you in advance for your help and wish you a good day !

Hardkaise

**Comment by nkast** [comment]
Hello @Hardkaise,
It's up to you how you translate and render the physics world into the screen.

I assume you are using SpriteBatch? The engine operates in Cartesian coordinates (left is Vector2.Left and up is Vector2.Up, (+1,0) & (0,+1) respectively) while SpriteBatch operates in ScreenCoordinates 
which is more suitable for GUI stuff (origin is at left-top corner and down is (0,+1)).

The HelloWorld sample demonstrates one approach on how to render the physics world into the screen.  It uses a custom Effect with SpriteBatch to pass a proper View+Projection matrix.
 
For hit-testing use Viewport.Project() to translate the hit point into the physics world coordinate.

**Comment by Hardkaise** [comment]
Thank you @nkast, 

Thanks to you I solved the problem. 

Unfortunately I have another issue: for the past few days, I've been trying to remove the limit on Body's LinearVelocity attribute but nothing works. I tried to use the VelocityLimitController class. So I instantiated my World, then create a VelocityLimitController while taking care to put the LinearVelocityLimit and AngularVelocityLimit fields to false, to add my VelocityLimitController via the Add function of my World object. I then added one by one the Bodies with DynamicBody as type in the VelocityLimitController but even so, the LinearVelocity contine to be blocked around X: 120 and Y: 0 when I head to the right while having set this LinearVelocity on my body at 500 for example.

Any help would be welcome

@Hardkaise

**Comment by nkast** [comment]
>> been trying to remove the limit on Body's LinearVelocity attribute but nothing works.

Controllers are kind of a plugin system that run automatically by World.Step().
I think I should remove them in the process of cleaning up the code as they were not part of Box2D and I don't think they have a place in the core simulation. Anyways...

The engine has build-in limits in settings.cs to avoid overshooting when things get unstable.
https://github.com/tainicom/Aether.Physics2D/blob/7f223ed0071f25b1607fc351ba42bf0a016bbefd/Physics2D/Settings.cs#L185-L189
I suppose if you run the engine at 60Hz (60fps) then 2m*60Hz = 120 m/s = 432 km/h. 
Are you using pixels as your unit? The engine is tuned to operate in K/M/S
https://github.com/erincatto/Box2D/wiki/FAQ#what-are-the-biggest-mistakes-made-by-new-users 



*Note to self: *
 The VelocityLimitController code seems to have a bug, it multiplies the the velocities (m/s) with the current dt (s) and compares the distances (m). 
https://github.com/tainicom/Aether.Physics2D/blob/master/Physics2D/Controllers/VelocityLimitController.cs#L96-L100
Then it seems like it uses the result which is distance (m) to scale the velocity (m/s). 
https://github.com/tainicom/Aether.Physics2D/blob/master/Physics2D/Controllers/VelocityLimitController.cs#L102-L106
This doen't look right, I need to take a second look on this.
