### ISSUE TITLE
Monogame reference

### ISSUE THREAD

**Issue by ApmeM** [tainicom/Aether.Physics2D#73]
Hi, 
I have a question - why do you have monogame reference from  your main physics engine?
In my view physics is just a math that is not view engine related.
What this reference is used for? I can see Point (but it is very simple class that can be reimplemented and mapped when needed).

**Comment by nkast** [comment]
You are right about that, I should provide a clean version that doesn't depend on MonoGame.
The main engine is using mainly the Vector2 struct and some math helpers.
 The are also some MonoGame features like importer, etc. Those will not be included in the clean version.

What platform(s) are you interested in? Dot.Net framework? Core/NetLibrary 2.0?

**Comment by ApmeM** [comment]
Dot.Net framework I think.

**Comment by brisingraerowing** [comment]
Making it a .NET Standard compliant library would allow use pretty much anywhere (Mono, .NETFx, .NET Core, etc), though I'm not sure if that would be possible.

**Comment by nkast** [comment]
The nuget is updated with v1.5.
No dependencies to 3rd party math libraries. 
Includes .net40 and netstandard2.0 assemblies.
