### ISSUE TITLE
Question - quick overlap detection

### ISSUE THREAD

**Issue by Fusionnist** [tainicom/Aether.Physics2D#78]
Hi,

Firstly, great thanks for the engine. It's saved my poor soul from hours of "figuring stuff out", and performs great in my current projects. Anyway, being terrible at finding documentation, here's my question: what's the most efficient way for checking whether two bodies overlap? I had been copying shapes and translating them, but those seem to demand heavy calculations from the engine. Is there a more straightforward way? 

Thank you for your time!

**Comment by nkast** [comment]
Hi @Fusionnist ,

There's are a couple of options, it depends on what you are trying to do. Here is quick summary: 

`World.ContactManager` has various Delegates/callbacks that are called during `World.Step(...)`. 
BeginContact / EndContact / ContactFilter / PreSolve/PostSolve. 
Body and Fixture has additional events, those were extensions added by Farseer).

After `World.Step(...)` you can iterate the `Body.ContactList` for active collisions.

The engine will prevent Dynamic bodies from overlapping unless if you set a fixture as a Sensor.

**Comment by Fusionnist** [comment]
Thank you for the answer; I should have mentioned: the bodies I wish to test for overlap here are not set to collide (their collision groups and collides with properties are set to prevent that). That might prevent any testing through the Step() phase or contact list. Is there a method you might be able to call on two fixtures to test or the likes?

**Comment by nkast** [comment]
Indeed, the collision groups is an early test and will not call any of the callbacks.

Some callbacks let's you return a boolean, if you return false it disables the contact. This let's you filter collisions on a body per body basis.  You can record the collision and then immediately disable the collision. I think it's also possible to disable the Contact by setting the `.Enable` property. 

However i think this will skip future Seperation/EndContact callbacks. If you are interested in those you could keep the collision groups as is and add identical Fixtures but this time set the IsSensor property. The sensors can be used to detect overlapping between those bodies. 


** edit **
ContactManager.ContactFilter comes from broadphase (after a quick AABB test but not an exact test). ContactManager.BeginContact and Fixture.OnCollision comes from narrowphase (actual collisions).

**Comment by Fusionnist** [comment]
Gotcha, I'll try that out. Thanks a lot!

As a note however, I previously used the following code:
(Where a and b are bodies, at and bt temp transform variables. There are a lot of assumptions made in the code, apologies for the messiness of it)

`Collision.TestOverlap(a_.FixtureList[0].Shape, 0, b_.FixtureList[0].Shape, 0, ref a_.GetTransform(out at),ref b_.GetTransform(out bt));`

This could be called at any moment in the code, but was very demanding of resources; would you know of a more optimal equivalent to this?

**Comment by nkast** [comment]
Not one that I know of. Looking at that method I think It should had been private in the first place.

**Comment by Fusionnist** [comment]
Got sensors working, problem solved! Thanks for the help!
