### ISSUE TITLE
Documentation completely absent?

### ISSUE THREAD

**Issue by Sheepyhead** [tainicom/Aether.Physics2D#80]
Hey there I couldn't help but notice that I can find absolutely zero documentation on this framework. It _seems_ to be very nicely designed, but it's hard to actually use since I can't really find any information about the API at all beyond the sparsely commented sample projects.

**Comment by Donaut** [comment]
Yeah, that's a big problem for the library.:( It makes a lot harder to use.

**Comment by Sheepyhead** [comment]
> 
> 
> Yeah, that's a big problem for the library.:( It makes a lot harder to use.

Fortunately for me my use case is pretty simple and this isn't a radically different physics engine from what I'm used to, but it does seem to be a significant lack

**Comment by bryanedds** [comment]
I find that opening the assembly up in something like ILSpy is extremely helpful for this purpose. Not only can you search and see all the types, you can easily navigate to any part of the implementation.

I know it's not the optimal replacement for documentation (or even a book), but in practice, I find it a reasonable substitute.

**Comment by andrew-sidereal** [comment]
You can largely refer to Box2D documentation: https://box2d.org/documentation/

Aether is a fork of Farseer Physics, which was a fork of Box2D. Some class names have evolved, some things have been altered and enhanced, but architecturally and conceptually it's still very close to Box2D.

**Comment by DaDarkWizard** [comment]
![this](https://user-images.githubusercontent.com/46545299/91497298-c61b5680-e88b-11ea-8c9f-181ba691f259.jpg)

**Comment by a-gt** [comment]
It would still be helpful if at least some documentation or tutorial was provided.
