### ISSUE TITLE
Extensive code duplication in ContactManager.cs -- any plan to reduce it?

### ISSUE THREAD

**Issue by andrew-sidereal** [tainicom/Aether.Physics2D#84]
I noticed ContactManager.cs has two methods: 
Collide()  -- inherited from Farseer
CollideMultiCore()  -- added in Aether

I understand this change was to facilitate the multi-threaded optimization, but having so much nearly identical code duplicated is a maintainability issue. I imagine there is a way to refactor it to re-use the similar collide logic, which accounts for something like 90% of the internal code of each method.

**Comment by nkast** [comment]
The required change was inside a loop which could potentially impact the performance in the single threaded mode.
I'd also like to avoid adding conditions in the code as in the future more things might change and make it harder to read that two separate clean methods.
