### ISSUE TITLE
Requesting advice for porting from Farseer.3.5.

### ISSUE THREAD

**Issue by bryanedds** [tainicom/Aether.Physics2D#85]
Hi!

I'm attempting to port this code from Farseer.3.5 physics (https://github.com/bryanedds/Nu/blob/master/Nu/Nu/Physics.fs).

However, Aether seems to be missing a few items compared to the last version of Farseer -

1. There's no UserData field on the Fixtures any more. I need this to correlate events on fixtures back to my scene graph.

2. Friction, Restitution, GravityScale, CollisionCategories, CollidesWith, and IsSensor setters are all missing on the Body class. Is there an alternate way to configure these items?

3. The BodyFactory and  FixtureFactories functions are all gone. I used these a lot. Is there a recommended alternative?

I fixed some of the errors in a branch here (https://github.com/bryanedds/Nu/tree/aether), but several remain. Any concrete advice you could give me on porting this stuff would be quite appreciated!

- Bryan

**Comment by nkast** [comment]
Hi, @bryanedds, 

1) body.UserData was renamed to body.Tag. Also changed to Field from Property.

2) Friction, Restitution, CollisionCategories, CollidesWith and IsSensor are properties of Fixture. Body has some methods to set all its fixtures to the same value, mybody.SetFriction(...), mybody.SetRestitution(...), etc.
GravityScale was removed. If you want to emulate the previous behavior you need to apply a counter-acting force on those bodies before every step.

3) Factories has been reworked. They are all prefixed with .Create...() , 
for example , myworld.CreateBody(), myworld.CreateCircle(...), mybody.CreateFixture(...), mybody.CreateEdge(...), etc
You should be able to see them. They are right here 
https://github.com/tainicom/Aether.Physics2D/blob/master/Physics2D/Dynamics/World.Factory.cs
https://github.com/tainicom/Aether.Physics2D/blob/master/Physics2D/Dynamics/Body.Factory.cs

**Comment by bryanedds** [comment]
This is great! I've fixed most of the compile errors, but the GravityScale is a challenge to fix efficiently. It wouldn't be very efficient for me to make my engine keep a list of bodies with irregular gravity scale and tell Aether to apply a force to them every frame.

Would it be possible to persuade you to consider to implement this functionality? Most platformers don't work with normal gravity scales (for example, my platformer characters all need a scale of 3.0 to not look and feel 'floaty'). It seems that implementing this feature on your side will be more efficient and make for a nicer API.

**Comment by bryanedds** [comment]
@nkast - I've worked around the lack of a GravityScale property by doing the following -

https://github.com/bryanedds/Nu/blob/735978d87db14f89d1805dc2f4535ae90cef1600/Nu/Nu/Physics.fs#L810-L813

Unfortunately, iterating through all physics bodies every frame is not very efficient compared to having the behavior integrated into the physics engine.

Would it make sense for me to open a separate issue requesting this feature?

**Comment by nkast** [comment]
I don't see GravityScale having a place in the engine, sorry.

In your implementation it's best to use ApplyForce() instead of directly changing the Velocity. If I remember correctly you need to multiply force by the body mass but not the time step.
About the performance, the first thing you can do is to skip Static and Kinematic objects early and avoid doing the calculation.
There's definitely room for improvements there. If physicsEngine is some abstraction of the physicsEngine then you can precalculate the needed force for each body (the force * mass), and or keep a seperate list of bodies that need to apply the GravityScale.

**Comment by bryanedds** [comment]
Ah, bummer. I do wonder what your reasoning for eschewing GravityScale is, if you don't mind.

As for this issue, I'll go ahead and close this as resolved - thanks for you help!
