### ISSUE TITLE
Using with System.Numerics vectors?

### ISSUE THREAD

**Issue by ThomasMiz** [tainicom/Aether.Physics2D#86]
I'm thinking about using this library, possibly for future projects.

I have standardized all my libraries to target .NET Standard 2.1 and use System.Numerics vectors, allowing me to use the same types across all of them (and also providing a nice perf boost where SIMD instructions are supported ;) ).

I'm guessing (though I'd like confirmation) that the library should work perfectly fine if I fork it and just replace all the VectorX to System.Numerics.VectorX and fill in the missing methods.

Also, is there a place (such as a discord server or discussions page) where I can ask simple questions that aren't big enough as to open an issue?

The library looks really cool, looking forward to trying it out!

**Comment by nkast** [comment]
I don't see why that wouldn't work, in fact a fork called AetherX has already done that. 
If you are using the MG version, they have added methods to convert Vector2 to System.Numerics.Vector2.

I don't currently have any forums, I think a discord channel will be a good addition.

**Comment by ThomasMiz** [comment]
I ended up modifying the library and yeah, it works just fine with System.Numerics if you resolve some conflicts with the vector methods. I noticed there are sometimes multiple versions of the same method to allow all parameters to be passed with or without ref, have you considered using passing the parameters as "in" instead? Or is supporting old language versions a requirement?

**Comment by nkast** [comment]
Currently `in` parameters create a defensive copy, unless you make the struct read-only. That's going to break a lot of code and I don't see the point since 'ref' works as well. After all, the target is to remove those helper methods in the future.

**Comment by nkast** [comment]
A discord channel is up: [https://discord.gg/95nPEjZ6mu](https://discord.gg/95nPEjZ6mu)
