### ISSUE TITLE
Hangs occasionally

### ISSUE THREAD

**Issue by Upcast-Eddie** [tainicom/Aether.Physics2D#88]
Sometimes (non deterministic) the program hangs. I could trace the cause back to Dynamic Tree.cs method InsertLeaf line 644: index = _nodes[index].ParentOrNext; ParentOrNext had the same value as index and the while loop was never ending.

**Comment by nkast** [comment]
The only way to address this is to provide a minimum sample that reproduces the problem.
Check your code if you are accessing the World from multiple threads without locking.

**Comment by nkast** [comment]
you need to catch when the tree becomes invalid. convert the ParentOrNext to a property and add your checks there. throw an exception if a node is set to point to itself. note the call stack and from which thread the change came from.
