### ISSUE TITLE
How to use Physics2DImporters

### ISSUE THREAD

**Issue by GeorgeA93** [tainicom/Aether.Physics2D#89]
Hi there, I am relatively new to monogame so apologies for the noob question. I was wondering how to setup the Physics2DImporters with the monogame content builder. I believe I need to add a reference to my content settings to a dll, but to which dll?

**Comment by nkast** [comment]
Hi,

Currently the importer is not available in binary form, you would need to download the latest release and build it yourself.
Once you have the DLL you will need to add a line like the following in .mgcb
https://github.com/tainicom/Aether.Physics2D/blob/master/Samples/NewSamplesContent/NewSamplesContent.mgcb#L13

'NewSamples' project has a couple of samples that make use of the pipeline importers/processors.

**Comment by GeorgeA93** [comment]
Ahhh that makes sense. Not sure why i didn't think of that. I'll give it a go, thank you.

**Comment by GeorgeA93** [comment]
That did the trick!
